travis:
  secure:
    BINSTAR_TOKEN: wagTPkfZCSyUphaXfoLa7DJrGqvjruz5qLGhDg1bVXxi37VKanOU9jGevBXfwugkljhxopGAuQR91irWfuQ1w7BVdZKd/kzak5P42l7biZN1Rhwi1r2OWv51cmsgFMiZQM+NPXUNMGVKZi1nV5kgg/haTwjFQXQ77IlV4Gqm+hW/MfkCwzmnXMCj/rSubbbwShSaZnT6KwYH+6p+Ag78JDZNaPGmS1dolWD19rq66jV6kCA0nhyvxtC7Nlo/7YjiJlfQGNOHPVfo1XxwjBbr3PA08fFk/JLjoYJO4VUJdHdX+LnKdf2kboh4H9SbaTK8B/XZOvJaGxssDIWpmo7jDcNmaQID82fPoh0j3c1uA+A1i05e5uHS8y35DeSeNi5Gy/JyZASTkhTea0tR/nELcKq8JB/XI2QQ9EduuUGCIki+tYYOoQCW4GCa8oxyKmXxtI30giLPhKk3AGsYMg06bI/LnIXVTmDO8p5/YnbfX550pjd724MGJV7d3JuzBZQNpJttihbCB+lfet/8s/R3RieBXp9CsqItIfOWUBMWURahYlWXQYROSyhcaRIZAKinPRypES7TRsStKnYgXBwH6KTiM6LayoyRfMZ/3hG4LeHUoNd1433X3eaZ3WfLDgRF7vUVi1eErk/7YKZ3hf07tJXaphV2wBi6rp6ZyzmJzr8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
